stf:
  image: chuross/stf-adb:latest
  container_name: stf
  privileged: true
  volumes:
    - /dev/bus/usb:/dev/bus/usb
  links:
    - rethinkdb
  ports:
    - 3000:3000
    - 7100:7100
    - 7110:7110
    - 7400-7700:7400-7700
  environment:
   STF_PUBLIC_IP: "${STF_PUBLIC_IP}"
  command: stf local --public-ip "${STF_PUBLIC_IP}"

rethinkdb:
  image: rethinkdb:latest
  container_name: rethinkdb
  ports:
    - 8080
    - 28015
    - 29015
